options:
  docker: true
 
image:
  name: tgalopin/maven-javafx

pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - cd launcher && mvn package
          - cd app && mvn test
    - step:
        name: Deploy Beta
        script:
          - cd app && mvn deploy -Dchannel=beta
        deployment: staging

  branches:
    master:
     - step:
        name: Deploy
        script:
          - cd app && mvn deploy -Dchannel=stable
        deployment: production
        