options:
  docker: true
 
image:
  name: maven:3.3.9-jdk-8

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - cd launcher && mvn package
            - cd app && mvn test
      - step:
          name: Deploy
          script:
            - cd app && mvn deploy -Dchannel=stable
          deployment: production
      