options:
  docker: true
 
image:
  name: 536482450038.dkr.ecr.ap-southeast-2.amazonaws.com/biggerconcept-mvn-jdk-agent:latest
  aws:
    access-key: $AWS_ACCESS_KEY_ID 
    secret-key: $AWS_SECRET_ACCESS_KEY

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - cd launcher && mvn package
            - Xvfb :99 &>/dev/null & export DISPLAY=:99 && cd app && mvn test
      - step:
          name: Deploy
          script:
            - cd app && mvn deploy -Dchannel=stable
          deployment: production
      